"""Initial migration

Revision ID: 6e97a233c897
Revises: 
Create Date: 2024-11-08 22:47:47.547804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e97a233c897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('contact')

    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_column('breed')
        batch_op.drop_column('age')
        batch_op.drop_column('species')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('breed', sa.VARCHAR(length=120), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('type')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=120), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
